# Vitenskapsfilosofi

**Oppgave 1: Gi en kort beskrivelse og forklaring av falsifikasjonisme. Presenter så ett problem med denne teorien. Tror du problemet kan løses? Begrunn svaret ditt**

Falsifikasjonisme, som ble introdusert av Karl Popper, har hatt en enorm innvirkning på vitenskapelig tenkning og metode. Det er imidlertid viktig å merke seg at falsifikasjonisme ikke er uten sine utfordringer og kritikk. Ifølge denne filosofien så kan kun en teori som kan falsifiseres bli kalt for vitenskapelig. Med dette menes det at det må være mulig å bevise at teorien er feil. Samtidig så argumenterte Popper på at ingen mengde observasjoner kunne si om en teori stemte, men at en enkelt observasjon kunne bevise at teorien er feil. [@mcleod2022] Da er tanken at vitenskapelig kunnskap alltids er tentativ og åpen for revisjon. Altså at det vitenskapen forteller oss ikke er fastsatt for alltid, men at den kan endres basert på nye observasjoner og oppdagelser.

Hvis man skal nevne et problem med denne teorien, kan man peke på utfordringen med hvordan teorier som blir testet, blir endret på for å passe til de observerte dataene. Dette er en betydelig bekymring fordi jo oftere en teori blir testet, desto mer spesifikk og kompleks vil teorien bli og dette kan øke kompleksiteten til det punktet hvor det kan være vanskelig å forstå eller anvende teorien i praksis. I tillegg kan overkomplisering av teorier føre til at de mister sin relevans, siden de da blir så spesifikke at de bare gjelder for et svært begrenset sett av situasjoner som gjør det vanskelig å reprodusere. Dette er et paradoks siden hensikten med en teori er å gi en generell forklaring på observasjonene. Derfor er det viktig å balansere behovet for nøyaktighet med behovet for anvendelighet når man utvikler og tester teorier.

For å unngå at man skal møte problemet med at teoriene blir for kompliserte kan vi bruke Occams barberblad prinsippet og Rema 1000 sitt slagord om at "det enkle er ofte det beste" altså at hvis en forsker sin teori om et emne blir motbevist etter forskningsstudiet hans, så istedenfor å overkomplisere den originale teorien han så bør han vurdere å legge fra seg teorien han hadde og komme opp med en nyere og enklere teori om hvorfor observasjonene hans ble slik som det ble.  

Selv om denne løsningen er relativt grei, så er sannheten også¨slik at av og til trenger teorien og være mer komplisert og vanskeligere å forstå for at den skal kunne beskrive observasjonene.

Til tross for disse utfordringene, har falsifikasjonisme fortsatt stor innflytelse på vitenskapen. Det har bidratt til å forme vitenskapelig metode og har fremmet ideen om at vitenskapelig kunnskap alltid er under utvikling og revisjon. Dette reflekterer den dynamiske naturen til vitenskapelig oppdagelse og fremgang. Å til slutt gjør det det viktig at forskerne prøver til sine beste mulige evner til å balansere simplisiteten og nøyaktigheten når de kommer med en teori.

**Oppgave 2: Forklar de grunnleggende ideene i Bayesianisme. Hva er noen av fordelene med Bayesianisme sammenlignet med alternativene? (for eksempel, HD-teorien eller abduktivisme). Presenter ett problem med Bayesianisme og evaluer hvor alvorlig problemet er.**

Ifølge @joyce2011 så tilbyr bayesiansime et kraftig sett med metoder for å trekke induktive slutninger, altså å kunne komme seg til en beslutning basert på informasjon man har fått som igjen kan være basert på observasjoner eller tidligere mønstre som man har observert. Bayesianisme brukes for å beskrive usikkerhet på ved statistikk, ved at den oppdaterer sannsynligheten når nye observasjoner eller ny informasjon blir tilgjengelig.

Skal man se på noen av de positive sidene med Bayesianisme så er Bayesianisme en teori som fokuserer mer på rasjonalitet enn valg som blir tatt grunnet følelser og egne meninger og ideer, som igjen lar oss ha en mer konsistent og sammenhengende tilnærming til håndtering og ta beslutninger. Dette er en egenskap som blir mer og mer aktuell for mer og mer komplekse scenarioer hvor man må ta mer og mer hensyn til usikkerhet som følge av flere faktorer. 

De som følger Bayesianisme følger sannsynlighetslovene hvor dette er grunnleggende for enhver statistisk analyse. Årsaken til dette er at dette hjelper med å sikre at dataene vi får er konsistente og veldefinerte. Som igjen styrkes av at overbevisningene baseres på et solid matematisk grunnlag. Dette hjelper også med å bekrefte og avkrefte observasjoner og teorier. Man kan jo si at dette er også det som styrker teorier som baserer seg på Bayesianisme siden alt blir "oppdatert"  så vil det si at jo fler observasjoner som blir gjort jo mer nøyaktig vil sannsynligheten for at en teori stemmer øke eller svekkes basert på hva dataen forteller oss.

Bayesianisme, som alle andre ideer, har sine negative sider og utfordringer. Selv om det gir en ramme for å ta mer konsistente og rasjonelle vurderinger, er det en risiko for at konklusjonene kan bli påvirket av subjektive priorer. Disse priorer er basert på personlig tro eller overbevisning før man ser på dataen, noe som betyr at man kan ha en viss bias før man rekker å se på data.

Dette er en utfordring med Bayesianisme, men alvorlighetsgraden er begrenset. Jo mer data man har, jo mindre vil subjektive meninger og oppfatninger kunne påvirke konklusjonene siden dataen da vil ha en sterkere sannsynlighet. Dette betyr at selv om subjektive priorer kan påvirke de tidlige stadiene av analysen, vil deres innflytelse avta etter hvert som mer data blir tilgjengelig. [@godfrey-smith2003]

Bayesianisme kan være et svært nyttig verktøy innenfor statistikk og vitenskapelig forskning. Det gir en kraftig metode for å lære fra data og oppdatere våre overbevisninger i lys av ny informasjon. Men som med alle verktøy, er det viktig å være klar over begrensningene til Bayesianisme og tenke nøye gjennom hvordan man bruker det. Ved å være bevisst på disse utfordringene, kan vi bruke Bayesianisme på en mer effektiv og ansvarlig måte.
